language: python
python:
- 3.6
script: pytest
env:
  - PYTHONPATH=.
before_deploy: echo Deploying to Pypi..
deploy:
  provider: pypi
  user: davidcarboni
  password:
    secure: e+xKDWQScuPRMMJgDdqLVWftpYowgwYthaFykmDeXrJIqRHYNzyP+NBG/PjhBUVR4gt9Xqq9nssrvUk7fvazkWfxTzpIsfOFV4314K5fzoUlKvXPIfazoKLaldQAhQDdvyGyvRJ/kly8/1+dx88GsEBRmKt7c9ovbT42bBCl4R4/HyO+ROGpUvOid0JqpZbNZ/Zw7snEaNgtFzFN27jM/MobLGojIX/hz5ADGCKcrbrBr8K0muUOSHkL8+xtQCi3GzlqDzFBb1Eqq1JoZZnAaBOqlR9GZ4aLWaNWORV+XdUVJf0gdi/h7lu8C6h8lm255MUa8a6q6Kk9b+sykOnuMkhHOg03PRSFbeoV0LNNEaix9xYuK/wx4t82xewST26Y6DZqLAniuBE8kdL4aNHRaBve9KPbVXldH5cEl/TuMCvBjyDAvOFWfh4pXSIym6tr1HCbaIwaf8bdKvEYSgDgG1BLIP3a8WxN/zCBjXIkvpqhARL3NwdesV5LuqhQqtzNWvfwQb7+DF+uy6OjLooAu9FHQbnVpxxWyXlbazx7skRkO2ph7SFVylk0/sEq+h2ApD3QVOXlB//G3JGz6ioincJkXjMW4H8AnydqZCXUxpt+ab9NJQHOC10sb5C3HGNoNvQB0BPasUm8Fkb4Tm/BfC247JBVVRYuUBTfWK6ra98=
  on:
    tags: true
    branch: master
after_deploy: echo Deployed to Pypi.
